name: template_expressions
description: A Dart library to process string based templates using expressions.
homepage: https://github.com/peiffer-innovations/template_expressions

version: 1.1.1+1

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  convert: ^3.0.1
  fake_async: ^1.2.0
  intl: ^0.17.0
  json_class: ^2.1.2+4
  json_path: ">=0.3.0 <0.5.0"
  meta: ^1.7.0
  petitparser: ">=4.0.2 <6.0.0"
  quiver: ^3.0.1+1
  rxdart: ^0.27.3

dev_dependencies:
  test: ^1.20.1
