name: 'template_expressions'
description: 'A Dart library to process string based templates using expressions.'
homepage: 'https://github.com/peiffer-innovations/template_expressions'
version: '1.1.7+3'

environment: 
  sdk: '>=2.17.0 <3.0.0'

dependencies: 
  convert: '^3.0.2'
  crypto: '^3.0.2'
  encrypt: '^5.0.1'
  fake_async: '^1.3.0'
  intl: '^0.17.0'
  json_class: '^2.1.2+8'
  json_path: '>=0.3.0 <0.5.0'
  logging: '^1.0.2'
  meta: '^1.7.0'
  petitparser: '>=4.0.2 <6.0.0'
  pointycastle: '^3.6.0'
  quiver: '^3.1.0'
  rxdart: '^0.27.4'
  yaon: '^1.0.1+3'

dev_dependencies: 
  test: '^1.21.4'

ignore_updates: 
  - 'async'
  - 'boolean_selector'
  - 'characters'
  - 'charcode'
  - 'collection'
  - 'clock'
  - 'fake_async'
  - 'file'
  - 'matcher'
  - 'material_color_utilities'
  - 'meta'
  - 'path'
  - 'source_span'
  - 'stack_trace'
  - 'stream_channel'
  - 'string_scanner'
  - 'term_glyph'
  - 'vector_math'
