name: template_expressions
description: A Dart library to process string based templates using expressions.
homepage: https://github.com/peiffer-innovations/template_expressions

version: 1.1.5

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  convert: ^3.0.1
  crypto: ^3.0.1
  encrypt: ^5.0.1
  fake_async: ^1.2.0
  intl: ^0.17.0
  json_class: ^2.1.2+4
  json_path: ">=0.3.0 <0.5.0"
  logging: ^1.0.2
  meta: ^1.7.0
  petitparser: ">=4.0.2 <6.0.0"
  pointycastle: ^3.5.2
  quiver: ^3.0.1+1
  rxdart: ^0.27.3
  yaon: ^1.0.0+1

dev_dependencies:
  test: ^1.21.0
